BUIDCo_ePMS.Web/Areas/AdminConsole/Controllers/TabMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BUIDCO.Domain.AdminConsole.TabMaster;
using BUIDCO.Repository.Contract.Contract.AdminConsole.ButtonMaster;
using BUIDCO.Repository.Contract.Contract.AdminConsole.TabMaster;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BUIDCO.Web.Areas.AdminConsole.Controllers
{
    [Area("AdminConsole")]
    public class TabMasterController : Controller
    {
        int intOut;
        public IButtonMasterServiceProvider _ButtonService { get; }
        public ITabMasterServiceProvider _TabMasterServiceProvider { get; }
        CreateTabMaster Model = new CreateTabMaster();
        public TabMasterController(IButtonMasterServiceProvider ButtonService, ITabMasterServiceProvider TabMasterServiceProvider)
        {
            _ButtonService = ButtonService;
            _TabMasterServiceProvider = TabMasterServiceProvider;
            
        }
        [HttpGet]
        public async Task<IActionResult> AddTab()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            {

                Model.ButtonList = (await _ButtonService.GetButton()).ButtonList.ToList();
                Model.INTCREATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));


                return View(Model);
            }
            else
            {
               return RedirectToAction("Logout", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> AddTabb()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            {

                Model.ButtonList = (await _ButtonService.GetButton()).ButtonList.ToList();
                Model.TabModelList = (await _TabMasterServiceProvider.GetMaxId()).ViewTabLinkDetails.ToList();
                Model.TMAxid = Model.TabModelList[0].TMAxid;
                Model.INTCREATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));


                return View(Model);
            }
            else
            {
               return RedirectToAction("Logout", "Home");
            }
        }
        [HttpPost]
        public ActionResult AddTabb(IFormCollection Coll, CreateTabMaster model, string Command)
        {
            if (Command == "Log")
            {
               
                return View();
            }

            if (Command == "Submit")
            {
                try
                {
                    if (ModelState.IsValid)
                    {

                        model.ActionCode = "A";
                        model.ButtonList = _ButtonService.GetButton().Result.ButtonList.ToList();
                        model.TabModelList = _TabMasterServiceProvider.GetMaxId().Result.ViewTabLinkDetails.ToList();
                        model.TMAxid = model.TabModelList[0].TMAxid;
                        model.INTBUTTONID = Convert.ToInt32(Coll["INTBUTTONID"]);
                        
                        model.NVCHTAB = Coll["NVCHTAB"].ToString();
                        model.NVCHDESCRIPTION = Coll["NVCHDESCRIPTION"].ToString();
                        model.VCHURL = Coll["VCHURL"].ToString();
                        model.intSortNum = Coll["intSortNum"].ToString();
                        if (Coll["CheckBoxAdd"].ToString() == "true,false")
                            model.FAdd = "Add";
                        else
                            model.FAdd = "N";
                        if (Coll["CheckBoxView"].ToString() == "true,false")
                            model.FView = "View";
                        else
                            model.FView = "N";
                        if (Coll["CheckBoxManage"].ToString() == "true,false")
                            model.FManage = "Manage";
                        else
                            model.FManage = "N";

                        model.INTCREATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));

                        intOut = _TabMasterServiceProvider.Addtabbmaster(model);
                        ViewData["result"] = intOut;
                        ModelState.Clear();
                        return View(model);
                    }
                    else
                    {
                        return View();
                    }
                }
                catch (Exception)
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("AddTabb");
            }

        }
        public ActionResult EditActiveTabb(string id)
        {
            try
            {
                
                CreateTabMaster model = new CreateTabMaster();
                model.ActionCode = "E";
                model.INTTABID = Convert.ToInt32(id);
                model.ButtonList = _ButtonService.GetButton().Result.ButtonList.ToList();
                IList<CreateTabMaster> objtabList = new List<CreateTabMaster>();
                objtabList = _TabMasterServiceProvider.GetAllTab(model);
                foreach (var i in objtabList)
                {
                    
                    model.INTBUTTONID = i.INTBUTTONID;
                    model.NVCHTAB = i.NVCHTAB;
                    model.intSortNum = i.intSortNum;
                    model.VCHURL = i.VCHURL;


                    ViewData["NVCHDESCRIPTION"] = i.NVCHDESCRIPTION;
                    
                    if (i.FAdd == "Add")
                        ViewData["FAdd"] = true;
                    else
                        ViewData["FAdd"] = false;
                    if (i.FView == "View")
                        ViewData["FView"] = true;
                    else
                        ViewData["FView"] = false;
                    if (i.FManage == "Manage")
                        ViewData["FManage"] = true;
                    else
                        ViewData["FManage"] = false;

                }
                return View(model);

            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult EditActiveTabb(string id, IFormCollection Coll, string Command)
        {
            if (Command == "Update")
            {
                
                Model.ActionCode = "U";
                Model.INTTABID = Convert.ToInt32(id);
                Model.INTBUTTONID = Convert.ToInt32(Coll["INTBUTTONID"]);
                Model.ButtonList = _ButtonService.GetButton().Result.ButtonList.ToList();
                Model.NVCHTAB = Coll["NVCHTAB"].ToString();
                Model.NVCHDESCRIPTION = Coll["NVCHDESCRIPTION"].ToString();
                Model.VCHURL = Coll["VCHURL"].ToString();
               // Model.intSortNum = Coll["intSortNum"].ToString();
                Model.NVCHDESCRIPTION = Coll["NVCHDESCRIPTION"].ToString();
                if (Coll["CheckBoxAdd"].ToString() == "true,false")
                    Model.FAdd = "Add";
                else
                    Model.FAdd = "N";
                if (Coll["CheckBoxView"].ToString() == "true,false")
                    Model.FView = "View";
                else
                    Model.FView = "N";
                if (Coll["CheckBoxManage"].ToString() == "true,false")
                    Model.FManage = "Manage";
                else
                    Model.FManage = "N";

                Model.INTCREATEDBY = Convert.ToInt32(HttpContext.Session.GetString("UserId"));// Convert.ToInt16(Session["UserId"]);
                intOut = _TabMasterServiceProvider.Edittabmaster(Model);

                if (intOut == 2)
                {

                    TempData["funresult"] = intOut;
                    TempData.Keep("funresult");
                    ModelState.Clear();

                    return RedirectToAction("ViewActiveTab", new { Status = TempData["result"] });
                }
                else
                {
                    TempData["funresult1"] = intOut;
                    TempData.Keep("funresult1");
                    ModelState.Clear();

                    return RedirectToAction("ViewActiveTab", new { Status = TempData["result1"] });
                }

            }
            else
            {
                return View();
            }
        }


        [HttpPost]
        public IActionResult ButtonTab(CreateTabMaster objbutton)
        {
            try
            {
                var Result = _TabMasterServiceProvider.AddTabmaster(objbutton);
                return RedirectToAction("ViewActiveTab", new { Status = "Record " + Result });



            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpGet]

        public async Task<IActionResult> ViewActiveTab(string Status)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            {
                try
                {
                    TabMasterModel model = new TabMasterModel();
                    model.TabList = (await _TabMasterServiceProvider.GetAllTabview(1)).TabList.ToList();
                    TempData["CommandStatus"] = Status;
                    return View(model);

                }
                catch (Exception ex)
                {

                    throw ex;
                }
            }
            else
            {
               return RedirectToAction("Logout", "Home");
            }



        }
        [HttpGet]
        public async Task<IActionResult>ViewInActiveTab(string Status)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UserId")))
            {
                try
                {
                    TabMasterModel model = new TabMasterModel();

BUIDCo_ePMS.Web/Areas/AdminConsole/Views/TabMaster/AddTab.cshtml
@model BUIDCO.Domain.AdminConsole.TabMaster.CreateTabMaster

@{
    Layout = "~/Areas/AdminConsole/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "AddTab";

}
@section Scripts {
    @*<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>*@

    <script type="text/javascript" language="javascript">
        function validateForm() {
            var x = document.forms["frmCreateTab"]["NVCHTAB"].value;

            if ($("#ddlbutton").val() == 0) {
                $("#ddlbutton").focus();
                alert("Please Select Button  Name.");

                return false;
            }
            else if ($("#txtTabName").val() == "") {
                $("#txtTabName").focus();
                alert(" Tab  Name Can't be blank.");

                return false;

            }
            else if ($("#txtTabURL").val() == "") {
                $("#txtTabURL").focus();
                alert("TAB URL Can't be blank.");

                return false;
            }
            else if ($("#txttabdescription").val() == "") {
                $("#txttabdescription").focus();
                alert("Tab Description Can't be blank.");

                return false;

            }
            else {
                return confirm('Are you sure you want to  create this?');
            }
        }

        function inputLimiter(e, allow) {
            var AllowableCharacters = '';

            if (allow == 'NameCharactersymbol') {
                AllowableCharacters = ' ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz./&';
            }
            if (allow == 'NameCharacters') {
                AllowableCharacters = ' ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz-.\'';
            }
            if (allow == 'Email') {
                AllowableCharacters = '1234567890@ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz_.';
            }
            if (allow == 'Description') {
                AllowableCharacters = '1234567890 ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz-.,()/';
            }
            if (allow == 'NameCharactersAndNumbers') {
                AllowableCharacters = '1234567890 ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz-,/.\&';
            }
            if (allow == 'Numbers') {
                AllowableCharacters = '1234567890';
            }
            if (allow == 'Decimal') {
                AllowableCharacters = '1234567890.';
            }
            if (allow == 'Filename') {
                AllowableCharacters = '1234567890ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz/';
            }
            var k;
            k = document.all ? parseInt(e.keyCode) : parseInt(e.which);
            if (k != 13 && k != 8 && k != 0) {
                if ((e.ctrlKey == false) && (e.altKey == false)) {
                    return (AllowableCharacters.indexOf(String.fromCharCode(k)) != -1);
                }
                else {
                    return true;
                }
            }
            else {
                return true;
            }
        }

        $(function () {
            $("#btnReset").bind("click", function () {
                $("#ddlbutton")[0].selectedIndex = 0;
                document.forms["frmCreateTab"]["NVCHTAB"].value = "";
                document.forms["frmCreateTab"]["VCHURL"].value = "";
                document.forms["frmCreateTab"]["NVCHDESCRIPTION"].value = "";
                document.forms["frmCreateTab"]["intSortNum"].value = "";
            });
        });
    </script>

  

}

<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Add Tab Master</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Tab Master</li>
                    <li class="breadcrumb-item active" aria-current="page">Add Tab Master</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link active" asp-area="AdminConsole" asp-controller="TabMaster" asp-action="AddTab">Add</a>
                        <a class="nav-item nav-link" asp-area="AdminConsole" asp-controller="TabMaster" asp-action="ViewActiveTab">Active</a>
                        <a class="nav-item nav-link" asp-area="AdminConsole" asp-controller="TabMaster" asp-action="ViewInActiveButton">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>
                <div class="card-body">
                    <form id="frmCreateTab" data-parsley-validate novalidate method="post" asp-action="ButtonTab" asp-area="AdminConsole" asp-controller="TabMaster" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Button Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <select id="ddlbutton" asp-for="INTBUTTONID" asp-items="@(new SelectList(Model.ButtonList,"INTBUTTONID","NVCHBUTTON"))" class="form-control">
                                    <option value="0">--Select Button Name --</option>
                                </select>
                            </div>

                        </div>

                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="NVCHTAB" id="txtTabName" class="form-control" placeholder="Enter Tab Name" autocomplete="off" maxlength="100" Onkeypress="return inputLimiter(event,'NameCharactersymbol')" />

                                <input asp-for="INTCREATEDBY" type="hidden" value='@ViewBag.CREATEDBY' />
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  URL
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="VCHURL" id="txtTabURL" class="form-control" placeholder="Enter Tab URL" autocomplete="off" maxlength="100" />

                                <input type="hidden" id="hdnparentid" />
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  Description
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="NVCHDESCRIPTION" id="txttabdescription" class="form-control" placeholder="Enter Button Description" autocomplete="off" maxlength="100" Onkeypress="return inputLimiter(event,'NameCharactersymbol')" />

                                <input type="hidden" id="hdnparentid" />
                            </div>


                        </div>



                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  Sortnum
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="intSortNum" id="txtbuttonsortnum" class="form-control" placeholder="Enter Button Sortnum" autocomplete="off" maxlength="100" Onkeypress="return inputLimiter(event,'Numbers')" />
                               
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"><span class="text-danger"></span></label>

                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon"></span>
                                <button type="submit" name="submit" id="btnsubmit" class="btn btn-primary mb-1t white-text" title="Submit" value="Submit">Submit</button>
                                <input type="button" id="btnReset" value="Reset" class="btn btn-danger" title="Reset" />
                            </div>
                        </div>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>

BUIDCo_ePMS.Web/Areas/AdminConsole/Views/TabMaster/EditActiveTab.cshtml
@model BUIDCO.Domain.AdminConsole.TabMaster.CreateTabMaster

@{
    Layout = "~/Areas/AdminConsole/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "EditActiveTab";

}
@section Scripts {
    @*<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>*@

    <script type="text/javascript" language="javascript">
        function validateForm() {
            var x = document.forms["frmCreateTab"]["NVCHTAB"].value;

            if ($("#ddlbutton").val() == 0) {
                $("#ddlbutton").focus();
                alert("Please Select Button  Name.");

                return false;
            }
            else if ($("#txtTabName").val() == "") {
                $("#txtTabName").focus();
                alert(" Tab  Name Can't be blank.");

                return false;

            }
            else if ($("#txtTabURL").val() == "") {
                $("#txtTabURL").focus();
                alert("TAB URL Can't be blank.");

                return false;
            }
            else if ($("#txttabdescription").val() == "") {
                $("#txttabdescription").focus();
                alert("Tab Description Can't be blank.");

                return false;

            }
            else {
                return confirm('Are you sure you want to  create this?');
            }
        }

        function inputLimiter(e, allow) {
            var AllowableCharacters = '';

            if (allow == 'NameCharactersymbol') {
                AllowableCharacters = ' ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz./&';
            }
            if (allow == 'NameCharacters') {
                AllowableCharacters = ' ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz-.\'';
            }
            if (allow == 'Email') {
                AllowableCharacters = '1234567890@ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz_.';
            }
            if (allow == 'Description') {
                AllowableCharacters = '1234567890 ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz-.,()/';
            }
            if (allow == 'NameCharactersAndNumbers') {
                AllowableCharacters = '1234567890 ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz-,/.\&';
            }
            if (allow == 'Numbers') {
                AllowableCharacters = '1234567890';
            }
            if (allow == 'Decimal') {
                AllowableCharacters = '1234567890.';
            }
            if (allow == 'Filename') {
                AllowableCharacters = '1234567890ABCDEFGHIBUIDCOLMNOPQRSTUVWXYZabcdefghiBUIDCOlmnopqrstuvwxyz/';
            }
            var k;
            k = document.all ? parseInt(e.keyCode) : parseInt(e.which);
            if (k != 13 && k != 8 && k != 0) {
                if ((e.ctrlKey == false) && (e.altKey == false)) {
                    return (AllowableCharacters.indexOf(String.fromCharCode(k)) != -1);
                }
                else {
                    return true;
                }
            }
            else {
                return true;
            }
        }

        $(function () {
            $("#btnReset").bind("click", function () {
                $("#ddlbutton")[0].selectedIndex = 0;
                document.forms["frmUpdateTab"]["NVCHTAB"].value = "";
            });
        });
    </script>

   

}

<div class="section">
    <div class="page-title">
        <div class="title-details">
            <h4>Add Tab Master</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><span class="icon-home1"></span></li>
                    <li class="breadcrumb-item">Tab Master</li>
                    <li class="breadcrumb-item active" aria-current="page">Add Tab Master</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                        <a class="nav-item nav-link active" asp-area="AdminConsole" asp-controller="TabMaster" asp-action="AddTabb">Add</a>
                        <a class="nav-item nav-link" asp-area="AdminConsole" asp-controller="TabMaster" asp-action="ViewActiveTab">Active</a>
                        <a class="nav-item nav-link" asp-area="AdminConsole" asp-controller="TabMaster" asp-action="ViewInActiveButton">InActive</a>
                    </ul>
                    <div class="indicatorslist">
                        <p class="ml-2 text-danger">(*) Indicates mandatory </p>
                    </div>
                </div>
                <div class="card-body">
                    <form id="frmUpdateTab" data-parsley-validate novalidate method="post" asp-area="AdminConsole" asp-action="EditButton" asp-controller="TabMaster" asp-area="" asp-antiforgery="true" onsubmit="return validateForm()">
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Button Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <select id="ddlbutton" asp-for="INTBUTTONID" asp-items="@(new SelectList(Model.ButtonList,"INTBUTTONID","NVCHBUTTON"))" class="form-control">
                                    <option value="0">--Select Button Name --</option>
                                </select>
                            </div>

                        </div>

                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  Name
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="NVCHTAB" id="txtTabName" class="form-control" placeholder="Enter Tab Name" autocomplete="off" maxlength="100" Onkeypress="return inputLimiter(event,'NameCharactersymbol')" />

                                <input asp-for="INTCREATEDBY" type="hidden" value='@ViewBag.CREATEDBY' />
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  URL
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="VCHURL" id="txtTabURL" class="form-control" placeholder="Enter Tab URL" autocomplete="off" maxlength="100" />

                                <input type="hidden" id="hdnparentid" />
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  Description
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="NVCHDESCRIPTION" id="txttabdescription" class="form-control" placeholder="Enter Button Description" autocomplete="off" maxlength="100" Onkeypress="return inputLimiter(event,'NameCharactersymbol')" />

                                <input type="hidden" id="hdnparentid" />
                            </div>


                        </div>



                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label">
                                Tab  Sortnum
                                <span class="text-danger">*</span>
                            </label>
                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon">:</span>
                                <input type="text" asp-for="intSortNum" id="txtbuttonsortnum" class="form-control" placeholder="Enter Button Sortnum" autocomplete="off" maxlength="100" Onkeypress="return inputLimiter(event,'Numbers')" />
                              
                            </div>


                        </div>
                        <div class="form-group row">
                            <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"><span class="text-danger"></span></label>

                            <div class="col-12 col-md-6 col-xl-4">
                                <span class="colon"></span>
                                <button type="submit" name="submit" id="btnsubmit" class="btn btn-primary mb-1t white-text" title="Submit" value="Submit">Update</button>
                                <input type="button" id="btnReset" value="Reset" class="btn btn-danger" title="Reset" />
                            </div>
                        </div>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>